name: 'Create Branch'
description: 'Creates a branch'
author: 'Peter Grainger (peter@grainger)'
branding:
  icon: 'git-branch' 
  color: 'green'
inputs:
  branch:
    description: 'The branch to create'
    default: 'release-candidate'
runs:
  using: 'node12'
  main: 'dist/index.js'
